application_repository = "https://github.com/arunsankar1314/training-arunsankar.online-repo"
project_name           = "trainingdevops"
project_env            = "production"
ami                    = "ami-0cc9838aa7ab1dce7"
instance_type          = "t2.micro"
